# Generated by Django 5.2.7 on 2025-10-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supplierprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierProfile',
        ),
    ]
