# Generated by Django 5.2.7 on 2025-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierprofile',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supplierprofile',
            old_name='contact_phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
