# Generated by Django 4.2.25 on 2025-10-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_contact_email_supplierprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_link',
            field=models.URLField(blank=True, null=True, verbose_name='购买链接'),
        ),
    ]
