# Generated by Django 5.2.7 on 2025-10-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_purchase_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='supplierprofile',
            options={'ordering': ['company_name', 'id'], 'verbose_name': 'Supplier profile', 'verbose_name_plural': 'Supplier profiles'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_link',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active (listed)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier'], name='products_pr_supplie_03c6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
    ]
