# Generated by Django 5.2.7 on 2025-11-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_alter_supplierprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_link',
            field=models.URLField(blank=True, null=True, verbose_name='Purchase Link'),
        ),
    ]
